BEGIN TRANSACTION;
DROP TABLE IF EXISTS Nobel;
CREATE TABLE IF NOT EXISTS Nobel
(
    annee   INT,
    sujet   VARCHAR(15),
    laureat VARCHAR(50)
);
INSERT INTO Nobel
VALUES (2008, 'Chimie', 'Martin Chalfie'),
       (2008, 'Chimie', 'Osamu Shimomura'),
       (2008, 'Chimie', 'Roger Y. Tsien'),
       (2008, 'Economie', 'Paul Krugman'),
       (2008, 'Literature', 'Jean-Marie Gustave Le Clézio'),
       (2008, 'Médecine', 'Françoise Barré-Sinoussi'),
       (2008, 'Médecine', 'Luc Montagnier'),
       (2008, 'Médecine', 'Harald zur Hausen'),
       (2008, 'Paix', 'Martti Ahtisaari'),
       (2008, 'Physique', 'Makoto Kobayashi'),
       (2008, 'Physique', 'Toshihide Maskawa'),
       (2008, 'Physique', 'Yoichiro Nambu'),
       (2007, 'Chimie', 'Gerhard Ertl'),
       (2007, 'Economie', 'Leonid Hurwicz'),
       (2007, 'Economie', 'Eric S. Maskin'),
       (2007, 'Economie', 'Roger B. Myerson'),
       (2007, 'Literature', 'Doris Lessing'),
       (2007, 'Médecine', 'Mario R. Capecchi'),
       (2007, 'Médecine', 'Sir Martin J. Evans'),
       (2007, 'Médecine', 'Oliver Smithies'),
       (2007, 'Paix', 'Intergovernmental Panel on Climate Change'),
       (2007, 'Paix', 'Al Gore'),
       (2007, 'Physique', 'Albert Fert'),
       (2007, 'Physique', 'Peter Grünberg'),
       (2006, 'Chimie', 'Roger D. Kornberg'),
       (2006, 'Economie', 'Edmund S. Phelps'),
       (2006, 'Literature', 'Orhan Pamuk'),
       (2006, 'Médecine', 'Andrew Z. Fire'),
       (2006, 'Médecine', 'Craig C. Mello'),
       (2006, 'Paix', 'Grameen Bank'),
       (2006, 'Paix', 'Muhammad Yunus'),
       (2006, 'Physique', 'John C. Mather'),
       (2006, 'Physique', 'George F. Smoot'),
       (2005, 'Chimie', 'Yves Chauvin'),
       (2005, 'Chimie', 'Robert H. Grubbs'),
       (2005, 'Chimie', 'Richard R. Schrock'),
       (2005, 'Economie', 'Robert J. Aumann'),
       (2005, 'Economie', 'Thomas C. Schelling'),
       (2005, 'Literature', 'Harold Pinter'),
       (2005, 'Médecine', 'Barry J. Marshall'),
       (2005, 'Médecine', 'J. Robin Warren'),
       (2005, 'Paix', 'International Atomic Energy Agency'),
       (2005, 'Paix', 'Mohamed ElBaradei'),
       (2005, 'Physique', 'Roy J. Glauber'),
       (2005, 'Physique', 'John L. Hall'),
       (2005, 'Physique', 'Theodor W. Hänsch'),
       (2004, 'Chimie', 'Aaron Ciechanover'),
       (2004, 'Chimie', 'Avram Hershko'),
       (2004, 'Chimie', 'Irwin Rose'),
       (2004, 'Economie', 'Finn E. Kydland'),
       (2004, 'Economie', 'Edward C. Prescott'),
       (2004, 'Literature', 'Elfriede Jelinek'),
       (2004, 'Médecine', 'Richard Axel'),
       (2004, 'Médecine', 'Linda B. Buck'),
       (2004, 'Paix', 'Wangari Maathai'),
       (2004, 'Physique', 'David J. Gross'),
       (2004, 'Physique', 'H. David Politzer'),
       (2004, 'Physique', 'Frank Wilczek'),
       (2003, 'Chimie', 'Peter Agre'),
       (2003, 'Chimie', 'Roderick MacKinnon'),
       (2003, 'Economie', 'Robert F. Engle III'),
       (2003, 'Economie', 'Clive W.J. Granger'),
       (2003, 'Literature', 'J. M. Coetzee'),
       (2003, 'Médecine', 'Paul C. Lauterbur'),
       (2003, 'Médecine', 'Sir Peter Mansfield'),
       (2003, 'Paix', 'Shirin Ebadi'),
       (2003, 'Physique', 'Alexei A. Abrikosov'),
       (2003, 'Physique', 'Vitaly L. Ginzburg'),
       (2003, 'Physique', 'Anthony J. Leggett'),
       (2002, 'Chimie', 'John B. Fenn'),
       (2002, 'Chimie', 'Koichi Tanaka'),
       (2002, 'Chimie', 'Kurt Wüthrich'),
       (2002, 'Economie', 'Daniel Kahneman'),
       (2002, 'Economie', 'Vernon L. Smith'),
       (2002, 'Literature', 'Imre Kertész'),
       (2002, 'Médecine', 'Sydney Brenner'),
       (2002, 'Médecine', 'H. Robert Horvitz'),
       (2002, 'Médecine', 'John E. Sulston'),
       (2002, 'Paix', 'Jimmy Carter'),
       (2002, 'Physique', 'Raymond Davis Jr.'),
       (2002, 'Physique', 'Riccardo Giacconi'),
       (2002, 'Physique', 'Masatoshi Koshiba'),
       (2001, 'Chimie', 'William S. Knowles'),
       (2001, 'Chimie', 'Ryoji Noyori'),
       (2001, 'Chimie', 'K. Barry Sharpless'),
       (2001, 'Economie', 'George A. Akerlof'),
       (2001, 'Economie', 'A. Michael Spence'),
       (2001, 'Economie', 'Joseph E. Stiglitz'),
       (2001, 'Literature', 'V. S. Naipaul'),
       (2001, 'Médecine', 'Leland H. Hartwell'),
       (2001, 'Médecine', 'Tim Hunt'),
       (2001, 'Médecine', 'Sir Paul Nurse'),
       (2001, 'Paix', 'United Nations'),
       (2001, 'Paix', 'Kofi Annan'),
       (2001, 'Physique', 'Eric A. Cornell'),
       (2001, 'Physique', 'Wolfgang Ketterle'),
       (2001, 'Physique', 'Carl E. Wieman'),
       (2000, 'Chimie', 'Alan Heeger'),
       (2000, 'Chimie', 'Alan G. MacDiarmid'),
       (2000, 'Chimie', 'Hideki Shirakawa'),
       (2000, 'Economie', 'James J. Heckman'),
       (2000, 'Economie', 'Daniel L. McFadden'),
       (2000, 'Literature', 'Gao Xingjian'),
       (2000, 'Médecine', 'Arvid Carlsson'),
       (2000, 'Médecine', 'Paul Greengard'),
       (2000, 'Médecine', 'Eric R. Kandel'),
       (2000, 'Paix', 'Kim Dae-jung'),
       (2000, 'Physique', 'Zhores I. Alferov'),
       (2000, 'Physique', 'Jack S. Kilby'),
       (2000, 'Physique', 'Herbert Kroemer'),
       (1999, 'Chimie', 'Ahmed Zewail'),
       (1999, 'Economie', 'Robert A. Mundell'),
       (1999, 'Literature', 'Günter Grass'),
       (1999, 'Médecine', 'Günter Blobel'),
       (1999, 'Paix', 'Médecins Sans Frontières'),
       (1999, 'Physique', 'Gerardus ''''t Hooft'),
       (1999, 'Physique', 'Martinus J.G. Veltman'),
       (1998, 'Chimie', 'Walter Kohn'),
       (1998, 'Chimie', 'John Pople'),
       (1998, 'Economie', 'Amartya Sen'),
       (1998, 'Literature', 'José Saramago'),
       (1998, 'Médecine', 'Robert F. Furchgott'),
       (1998, 'Médecine', 'Louis J. Ignarro'),
       (1998, 'Médecine', 'Ferid Murad'),
       (1998, 'Paix', 'John Hume'),
       (1998, 'Paix', 'David Trimble'),
       (1998, 'Physique', 'Robert B. Laughlin'),
       (1998, 'Physique', 'Horst L. Störmer'),
       (1998, 'Physique', 'Daniel C. Tsui'),
       (1997, 'Chimie', 'Paul D. Boyer'),
       (1997, 'Chimie', 'Jens C. Skou'),
       (1997, 'Chimie', 'John E. Walker'),
       (1997, 'Economie', 'Robert C. Merton'),
       (1997, 'Economie', 'Myron S. Scholes'),
       (1997, 'Literature', 'Dario Fo'),
       (1997, 'Médecine', 'Stanley B. Prusiner'),
       (1997, 'Paix', 'International Campaign to Ban Landmines'),
       (1997, 'Paix', 'Jody Williams'),
       (1997, 'Physique', 'Steven Chu'),
       (1997, 'Physique', 'Claude Cohen-Tannoudji'),
       (1997, 'Physique', 'William D. Phillips'),
       (1996, 'Chimie', 'Robert F. Curl Jr.'),
       (1996, 'Chimie', 'Sir Harold Kroto'),
       (1996, 'Chimie', 'Richard E. Smalley'),
       (1996, 'Economie', 'James A. Mirrlees'),
       (1996, 'Economie', 'William Vickrey'),
       (1996, 'Literature', 'Wislawa Szymborska'),
       (1996, 'Médecine', 'Peter C. Doherty'),
       (1996, 'Médecine', 'Rolf M. Zinkernagel'),
       (1996, 'Paix', 'Carlos Filipe Ximenes Belo'),
       (1996, 'Paix', 'José Ramos-Horta'),
       (1996, 'Physique', 'David M. Lee'),
       (1996, 'Physique', 'Douglas D. Osheroff'),
       (1996, 'Physique', 'Robert C. Richardson'),
       (1995, 'Chimie', 'Paul J. Crutzen'),
       (1995, 'Chimie', 'Mario J. Molina'),
       (1995, 'Chimie', 'F. Sherwood Rowland'),
       (1995, 'Economie', 'Robert E. Lucas Jr.'),
       (1995, 'Literature', 'Seamus Heaney'),
       (1995, 'Médecine', 'Edward B. Lewis'),
       (1995, 'Médecine', 'Christiane Nüsslein-Volhard'),
       (1995, 'Médecine', 'Eric F. Wieschaus'),
       (1995, 'Paix', 'Pugwash Conferences on Science and World Affairs'),
       (1995, 'Paix', 'Joseph Rotblat'),
       (1995, 'Physique', 'Martin L. Perl'),
       (1995, 'Physique', 'Frederick Reines'),
       (1994, 'Chimie', 'George A. Olah'),
       (1994, 'Economie', 'John C. Harsanyi'),
       (1994, 'Economie', 'John F. Nash Jr.'),
       (1994, 'Economie', 'Reinhard Selten'),
       (1994, 'Literature', 'Kenzaburo Oe'),
       (1994, 'Médecine', 'Alfred G. Gilman'),
       (1994, 'Médecine', 'Martin Rodbell'),
       (1994, 'Paix', 'Yasser Arafat'),
       (1994, 'Paix', 'Shimon Peres'),
       (1994, 'Paix', 'Yitzhak Rabin'),
       (1994, 'Physique', 'Bertram N. Brockhouse'),
       (1994, 'Physique', 'Clifford G. Shull'),
       (1993, 'Chimie', 'Kary B. Mullis'),
       (1993, 'Chimie', 'Michael Smith'),
       (1993, 'Economie', 'Robert W. Fogel'),
       (1993, 'Economie', 'Douglass C. North'),
       (1993, 'Literature', 'Toni Morrison'),
       (1993, 'Médecine', 'Richard J. Roberts'),
       (1993, 'Médecine', 'Phillip A. Sharp'),
       (1993, 'Paix', 'F.W. de Klerk'),
       (1993, 'Paix', 'Nelson Mandela'),
       (1993, 'Physique', 'Russell A. Hulse'),
       (1993, 'Physique', 'Joseph H. Taylor Jr.'),
       (1992, 'Chimie', 'Rudolph A. Marcus'),
       (1992, 'Economie', 'Gary S. Becker'),
       (1992, 'Literature', 'Derek Walcott'),
       (1992, 'Médecine', 'Edmond H. Fischer'),
       (1992, 'Médecine', 'Edwin G. Krebs'),
       (1992, 'Paix', 'Rigoberta Menchú Tum'),
       (1992, 'Physique', 'Georges Charpak'),
       (1991, 'Chimie', 'Richard R. Ernst'),
       (1991, 'Economie', 'Ronald H. Coase'),
       (1991, 'Literature', 'Nadine Gordimer'),
       (1991, 'Médecine', 'Erwin Neher'),
       (1991, 'Médecine', 'Bert Sakmann'),
       (1991, 'Paix', 'Aung San Suu Kyi'),
       (1991, 'Physique', 'Pierre-Gilles de Gennes'),
       (1990, 'Chimie', 'Elias James Corey'),
       (1990, 'Economie', 'Harry M. Markowitz'),
       (1990, 'Economie', 'Merton H. Miller'),
       (1990, 'Economie', 'William F. Sharpe'),
       (1990, 'Literature', 'Octavio Paz'),
       (1990, 'Médecine', 'Joseph E. Murray'),
       (1990, 'Médecine', 'E. Donnall Thomas'),
       (1990, 'Paix', 'Mikhail Gorbachev'),
       (1990, 'Physique', 'Jerome I. Friedman'),
       (1990, 'Physique', 'Henry W. Kendall'),
       (1990, 'Physique', 'Richard E. Taylor'),
       (1989, 'Chimie', 'Sidney Altman'),
       (1989, 'Chimie', 'Thomas R. Cech'),
       (1989, 'Economie', 'Trygve Haavelmo'),
       (1989, 'Literature', 'Camilo José Cela'),
       (1989, 'Médecine', 'J. Michael Bishop'),
       (1989, 'Médecine', 'Harold E. Varmus'),
       (1989, 'Paix', 'The 14th Dalai Lama'),
       (1989, 'Physique', 'Hans G. Dehmelt'),
       (1989, 'Physique', 'Wolfgang Paul'),
       (1989, 'Physique', 'Norman F. Ramsey'),
       (1988, 'Chimie', 'Johann Deisenhofer'),
       (1988, 'Chimie', 'Robert Huber'),
       (1988, 'Chimie', 'Hartmut Michel'),
       (1988, 'Economie', 'Maurice Allais'),
       (1988, 'Literature', 'Naguib Mahfouz'),
       (1988, 'Médecine', 'Sir James W. Black'),
       (1988, 'Médecine', 'Gertrude B. Elion'),
       (1988, 'Médecine', 'George H. Hitchings'),
       (1988, 'Paix', 'United Nations Paixkeeping Forces'),
       (1988, 'Physique', 'Leon M. Lederman'),
       (1988, 'Physique', 'Melvin Schwartz'),
       (1988, 'Physique', 'Jack Steinberger'),
       (1987, 'Chimie', 'Donald J. Cram'),
       (1987, 'Chimie', 'Jean-Marie Lehn'),
       (1987, 'Chimie', 'Charles J. Pedersen'),
       (1987, 'Economie', 'Robert M. Solow'),
       (1987, 'Literature', 'Joseph Brodsky'),
       (1987, 'Médecine', 'Susumu Tonegawa'),
       (1987, 'Paix', 'Oscar Arias Sánchez'),
       (1987, 'Physique', 'J. Georg Bednorz'),
       (1987, 'Physique', 'K. Alex Müller'),
       (1986, 'Chimie', 'Dudley R. Herschbach'),
       (1986, 'Chimie', 'Yuan T. Lee'),
       (1986, 'Chimie', 'John C. Polanyi'),
       (1986, 'Economie', 'James M. Buchanan Jr.'),
       (1986, 'Literature', 'Wole Soyinka'),
       (1986, 'Médecine', 'Stanley Cohen'),
       (1986, 'Médecine', 'Rita Levi-Montalcini'),
       (1986, 'Paix', 'Elie Wiesel'),
       (1986, 'Physique', 'Gerd Binnig'),
       (1986, 'Physique', 'Heinrich Rohrer'),
       (1986, 'Physique', 'Ernst Ruska'),
       (1985, 'Chimie', 'Herbert A. Hauptman'),
       (1985, 'Chimie', 'Jerome Karle'),
       (1985, 'Economie', 'Franco Modigliani'),
       (1985, 'Literature', 'Claude Simon'),
       (1985, 'Médecine', 'Michael S. Brown'),
       (1985, 'Médecine', 'Joseph L. Goldstein'),
       (1985, 'Paix', 'International Physicians for the Prevention of Nuclear War'),
       (1985, 'Physique', 'Klaus von Klitzing'),
       (1984, 'Chimie', 'Bruce Merrifield'),
       (1984, 'Economie', 'Richard Stone'),
       (1984, 'Literature', 'Jaroslav Seifert'),
       (1984, 'Médecine', 'Niels K. Jerne'),
       (1984, 'Médecine', 'Georges J.F. Köhler'),
       (1984, 'Médecine', 'César Milstein'),
       (1984, 'Paix', 'Desmond Tutu'),
       (1984, 'Physique', 'Carlo Rubbia'),
       (1984, 'Physique', 'Simon van der Meer'),
       (1983, 'Chimie', 'Henry Taube'),
       (1983, 'Economie', 'Gerard Debreu'),
       (1983, 'Literature', 'William Golding'),
       (1983, 'Médecine', 'Barbara McClintock'),
       (1983, 'Paix', 'Lech Walesa'),
       (1983, 'Physique', 'Subramanyan Chandrasekhar'),
       (1983, 'Physique', 'William A. Fowler'),
       (1982, 'Chimie', 'Aaron Klug'),
       (1982, 'Economie', 'George J. Stigler'),
       (1982, 'Literature', 'Gabriel García Márquez'),
       (1982, 'Médecine', 'Sune K. Bergström'),
       (1982, 'Médecine', 'Bengt I. Samuelsson'),
       (1982, 'Médecine', 'John R. Vane'),
       (1982, 'Paix', 'Alfonso García Robles'),
       (1982, 'Paix', 'Alva Myrdal'),
       (1982, 'Physique', 'Kenneth G. Wilson'),
       (1981, 'Chimie', 'Kenichi Fukui'),
       (1981, 'Chimie', 'Roald Hoffmann'),
       (1981, 'Economie', 'James Tobin'),
       (1981, 'Literature', 'Elias Canetti'),
       (1981, 'Médecine', 'David H. Hubel'),
       (1981, 'Médecine', 'Roger W. Sperry'),
       (1981, 'Médecine', 'Torsten N. Wiesel'),
       (1981, 'Paix', 'Office of the United Nations High Commissioner for Refugees'),
       (1981, 'Physique', 'Nicolaas Bloembergen'),
       (1981, 'Physique', 'Arthur L. Schawlow'),
       (1981, 'Physique', 'Kai M. Siegbahn'),
       (1980, 'Chimie', 'Paul Berg'),
       (1980, 'Chimie', 'Walter Gilbert'),
       (1980, 'Chimie', 'Frederick Sanger'),
       (1980, 'Economie', 'Lawrence R. Klein'),
       (1980, 'Literature', 'Czeslaw Milosz'),
       (1980, 'Médecine', 'Baruj Benacerraf'),
       (1980, 'Médecine', 'Jean Dausset'),
       (1980, 'Médecine', 'George D. Snell'),
       (1980, 'Paix', 'Adolfo Pérez Esquivel'),
       (1980, 'Physique', 'James Cronin'),
       (1980, 'Physique', 'Val Fitch'),
       (1979, 'Chimie', 'Herbert C. Brown'),
       (1979, 'Chimie', 'Georg Wittig'),
       (1979, 'Economie', 'Sir Arthur Lewis'),
       (1979, 'Economie', 'Theodore W. Schultz'),
       (1979, 'Literature', 'Odysseus Elytis'),
       (1979, 'Médecine', 'Allan M. Cormack'),
       (1979, 'Médecine', 'Godfrey N. Hounsfield'),
       (1979, 'Paix', 'Mother Teresa'),
       (1979, 'Physique', 'Sheldon Glashow'),
       (1979, 'Physique', 'Abdus Salam'),
       (1979, 'Physique', 'Steven Weinberg'),
       (1978, 'Chimie', 'Peter Mitchell'),
       (1978, 'Economie', 'Herbert A. Simon'),
       (1978, 'Literature', 'Isaac Bashevis Singer'),
       (1978, 'Médecine', 'Werner Arber'),
       (1978, 'Médecine', 'Daniel Nathans'),
       (1978, 'Médecine', 'Hamilton O. Smith'),
       (1978, 'Paix', 'Anwar al-Sadat'),
       (1978, 'Paix', 'Menachem Begin'),
       (1978, 'Physique', 'Pyotr Kapitsa'),
       (1978, 'Physique', 'Arno Penzias'),
       (1978, 'Physique', 'Robert Woodrow Wilson'),
       (1977, 'Chimie', 'Ilya Prigogine'),
       (1977, 'Economie', 'James E. Meade'),
       (1977, 'Economie', 'Bertil Ohlin'),
       (1977, 'Literature', 'Vicente Aleixandre'),
       (1977, 'Médecine', 'Roger Guillemin'),
       (1977, 'Médecine', 'Andrew V. Schally'),
       (1977, 'Médecine', 'Rosalyn Yalow'),
       (1977, 'Paix', 'Amnesty International'),
       (1977, 'Physique', 'Philip W. Anderson'),
       (1977, 'Physique', 'Sir Nevill F. Mott'),
       (1977, 'Physique', 'John H. van Vleck'),
       (1976, 'Chimie', 'William Lipscomb'),
       (1976, 'Economie', 'Milton Friedman'),
       (1976, 'Literature', 'Saul Bellow'),
       (1976, 'Médecine', 'Baruch S. Blumberg'),
       (1976, 'Médecine', 'D. Carleton Gajdusek'),
       (1976, 'Paix', 'Mairead Corrigan'),
       (1976, 'Paix', 'Betty Williams'),
       (1976, 'Physique', 'Burton Richter'),
       (1976, 'Physique', 'Samuel C.C. Ting'),
       (1975, 'Chimie', 'John Cornforth'),
       (1975, 'Chimie', 'Vladimir Prelog'),
       (1975, 'Economie', 'Leonid Vitaliyevich Kantorovich'),
       (1975, 'Economie', 'Tjalling C. Koopmans'),
       (1975, 'Literature', 'Eugenio Montale'),
       (1975, 'Médecine', 'David Baltimore'),
       (1975, 'Médecine', 'Renato Dulbecco'),
       (1975, 'Médecine', 'Howard M. Temin'),
       (1975, 'Paix', 'Andrei Sakharov'),
       (1975, 'Physique', 'Aage N. Bohr'),
       (1975, 'Physique', 'Ben R. Mottelson'),
       (1975, 'Physique', 'James Rainwater'),
       (1974, 'Chimie', 'Paul J. Flory'),
       (1974, 'Economie', 'Gunnar Myrdal'),
       (1974, 'Economie', 'Friedrich August von Hayek'),
       (1974, 'Literature', 'Eyvind Johnson'),
       (1974, 'Literature', 'Harry Martinson'),
       (1974, 'Médecine', 'Albert Claude'),
       (1974, 'Médecine', 'Christian de Duve'),
       (1974, 'Médecine', 'George E. Palade'),
       (1974, 'Paix', 'Seán MacBride'),
       (1974, 'Paix', 'Eisaku Sato'),
       (1974, 'Physique', 'Antony Hewish'),
       (1974, 'Physique', 'Martin Ryle'),
       (1973, 'Chimie', 'Ernst Otto Fischer'),
       (1973, 'Chimie', 'Geoffrey Wilkinson'),
       (1973, 'Economie', 'Wassily Leontief'),
       (1973, 'Literature', 'Patrick White'),
       (1973, 'Médecine', 'Konrad Lorenz'),
       (1973, 'Médecine', 'Nikolaas Tinbergen'),
       (1973, 'Médecine', 'Karl von Frisch'),
       (1973, 'Paix', 'Le Duc Tho'),
       (1973, 'Paix', 'Henry Kissinger'),
       (1973, 'Physique', 'Leo Esaki'),
       (1973, 'Physique', 'Ivar Giaever'),
       (1973, 'Physique', 'Brian D. Josephson'),
       (1972, 'Chimie', 'Christian Anfinsen'),
       (1972, 'Chimie', 'Stanford Moore'),
       (1972, 'Chimie', 'William H. Stein'),
       (1972, 'Economie', 'Kenneth J. Arrow'),
       (1972, 'Economie', 'John R. Hicks'),
       (1972, 'Literature', 'Heinrich Böll'),
       (1972, 'Médecine', 'Gerald M. Edelman'),
       (1972, 'Médecine', 'Rodney R. Porter'),
       (1972, 'Physique', 'John Bardeen'),
       (1972, 'Physique', 'Leon N. Cooper'),
       (1972, 'Physique', 'Robert Schrieffer'),
       (1971, 'Chimie', 'Gerhard Herzberg'),
       (1971, 'Economie', 'Simon Kuznets'),
       (1971, 'Literature', 'Pablo Neruda'),
       (1971, 'Médecine', 'Earl W. Sutherland, Jr.'),
       (1971, 'Paix', 'Willy Brandt'),
       (1971, 'Physique', 'Dennis Gabor'),
       (1970, 'Chimie', 'Luis Leloir'),
       (1970, 'Economie', 'Paul A. Samuelson'),
       (1970, 'Literature', 'Alexandr Solzhenitsyn'),
       (1970, 'Médecine', 'Julius Axelrod'),
       (1970, 'Médecine', 'Sir Bernard Katz'),
       (1970, 'Médecine', 'Ulf von Euler'),
       (1970, 'Paix', 'Norman Borlaug'),
       (1970, 'Physique', 'Hannes Alfvén'),
       (1970, 'Physique', 'Louis Néel'),
       (1969, 'Chimie', 'Derek Barton'),
       (1969, 'Chimie', 'Odd Hassel'),
       (1969, 'Economie', 'Ragnar Frisch'),
       (1969, 'Economie', 'Jan Tinbergen'),
       (1969, 'Literature', 'Samuel Beckett'),
       (1969, 'Médecine', 'Max Delbrück'),
       (1969, 'Médecine', 'Alfred D. Hershey'),
       (1969, 'Médecine', 'Salvador E. Luria'),
       (1969, 'Paix', 'International Labour Organization'),
       (1969, 'Physique', 'Murray Gell-Mann'),
       (1968, 'Chimie', 'Lars Onsager'),
       (1968, 'Literature', 'Yasunari Kawabata'),
       (1968, 'Médecine', 'Robert W. Holley'),
       (1968, 'Médecine', 'H. Gobind Khorana'),
       (1968, 'Médecine', 'Marshall W. Nirenberg'),
       (1968, 'Paix', 'René Cassin'),
       (1968, 'Physique', 'Luis Alvarez'),
       (1967, 'Chimie', 'Manfred Eigen'),
       (1967, 'Chimie', 'Ronald G.W. Norrish'),
       (1967, 'Chimie', 'George Porter'),
       (1967, 'Literature', 'Miguel Angel Asturias'),
       (1967, 'Médecine', 'Ragnar Granit'),
       (1967, 'Médecine', 'Haldan K. Hartline'),
       (1967, 'Médecine', 'George Wald'),
       (1967, 'Physique', 'Hans Bethe'),
       (1966, 'Chimie', 'Robert S. Mulliken'),
       (1966, 'Literature', 'Shmuel Agnon'),
       (1966, 'Literature', 'Nelly Sachs'),
       (1966, 'Médecine', 'Charles B. Huggins'),
       (1966, 'Médecine', 'Peyton Rous'),
       (1966, 'Physique', 'Alfred Kastler'),
       (1965, 'Chimie', 'Robert B. Woodward'),
       (1965, 'Literature', 'Mikhail Sholokhov'),
       (1965, 'Médecine', 'François Jacob'),
       (1965, 'Médecine', 'André Lwoff'),
       (1965, 'Médecine', 'Jacques Monod'),
       (1965, 'Paix', 'United Nations Children''''s Fund'),
       (1965, 'Physique', 'Richard P. Feynman'),
       (1965, 'Physique', 'Julian Schwinger'),
       (1965, 'Physique', 'Sin-Itiro Tomonaga'),
       (1964, 'Chimie', 'Dorothy Crowfoot Hodgkin'),
       (1964, 'Literature', 'Jean-Paul Sartre'),
       (1964, 'Médecine', 'Konrad Bloch'),
       (1964, 'Médecine', 'Feodor Lynen'),
       (1964, 'Paix', 'Martin Luther King Jr.'),
       (1964, 'Physique', 'Nicolay G. Basov'),
       (1964, 'Physique', 'Aleksandr M. Prokhorov'),
       (1964, 'Physique', 'Charles H. Townes'),
       (1963, 'Chimie', 'Giulio Natta'),
       (1963, 'Chimie', 'Karl Ziegler'),
       (1963, 'Literature', 'Giorgos Seferis'),
       (1963, 'Médecine', 'Sir John Eccles'),
       (1963, 'Médecine', 'Alan L. Hodgkin'),
       (1963, 'Médecine', 'Andrew F. Huxley'),
       (1963, 'Paix', 'International Committee of the Red Cross'),
       (1963, 'Paix', 'League of Red Cross Societies'),
       (1963, 'Physique', 'Maria Goeppert-Mayer'),
       (1963, 'Physique', 'J. Hans D. Jensen'),
       (1963, 'Physique', 'Eugene Wigner'),
       (1962, 'Chimie', 'John C. Kendrew'),
       (1962, 'Chimie', 'Max F. Perutz'),
       (1962, 'Literature', 'John Steinbeck'),
       (1962, 'Médecine', 'Francis Crick'),
       (1962, 'Médecine', 'James Watson'),
       (1962, 'Médecine', 'Maurice Wilkins'),
       (1962, 'Paix', 'Linus Pauling'),
       (1962, 'Physique', 'Lev Landau'),
       (1961, 'Chimie', 'Melvin Calvin'),
       (1961, 'Literature', 'Ivo Andric'),
       (1961, 'Médecine', 'Georg von Békésy'),
       (1961, 'Paix', 'Dag Hammarskjöld'),
       (1961, 'Physique', 'Robert Hofstadter'),
       (1961, 'Physique', 'Rudolf Mössbauer'),
       (1960, 'Chimie', 'Willard F. Libby'),
       (1960, 'Literature', 'Saint-John Perse'),
       (1960, 'Médecine', 'Sir Frank Macfarlane Burnet'),
       (1960, 'Médecine', 'Peter Medawar'),
       (1960, 'Paix', 'Albert Lutuli'),
       (1960, 'Physique', 'Donald A. Glaser'),
       (1959, 'Chimie', 'Jaroslav Heyrovsky'),
       (1959, 'Literature', 'Salvatore Quasimodo'),
       (1959, 'Médecine', 'Arthur Kornberg'),
       (1959, 'Médecine', 'Severo Ochoa'),
       (1959, 'Paix', 'Philip Noel-Baker'),
       (1959, 'Physique', 'Owen Chamberlain'),
       (1959, 'Physique', 'Emilio Segrè'),
       (1958, 'Chimie', 'Frederick Sanger'),
       (1958, 'Literature', 'Boris Pasternak'),
       (1958, 'Médecine', 'George Beadle'),
       (1958, 'Médecine', 'Joshua Lederberg'),
       (1958, 'Médecine', 'Edward Tatum'),
       (1958, 'Paix', 'Georges Pire'),
       (1958, 'Physique', 'Pavel A. Cherenkov'),
       (1958, 'Physique', 'Il´ja M. Frank'),
       (1958, 'Physique', 'Igor Y. Tamm'),
       (1957, 'Chimie', 'Lord Todd'),
       (1957, 'Literature', 'Albert Camus'),
       (1957, 'Médecine', 'Daniel Bovet'),
       (1957, 'Paix', 'Lester Bowles Pearson'),
       (1957, 'Physique', 'Tsung-Dao Lee'),
       (1957, 'Physique', 'Chen Ning Yang'),
       (1956, 'Chimie', 'Sir Cyril Hinshelwood'),
       (1956, 'Chimie', 'Nikolay Semenov'),
       (1956, 'Literature', 'Juan Ramón Jiménez'),
       (1956, 'Médecine', 'André F. Cournand'),
       (1956, 'Médecine', 'Werner Forssmann'),
       (1956, 'Médecine', 'Dickinson W. Richards'),
       (1956, 'Physique', 'John Bardeen'),
       (1956, 'Physique', 'Walter H. Brattain'),
       (1956, 'Physique', 'William B. Shockley'),
       (1955, 'Chimie', 'Vincent du Vigneaud'),
       (1955, 'Literature', 'Halldór Laxness'),
       (1955, 'Médecine', 'Hugo Theorell'),
       (1955, 'Physique', 'Polykarp Kusch'),
       (1955, 'Physique', 'Willis E. Lamb'),
       (1954, 'Chimie', 'Linus Pauling'),
       (1954, 'Literature', 'Ernest Hemingway'),
       (1954, 'Médecine', 'John F. Enders'),
       (1954, 'Médecine', 'Frederick C. Robbins'),
       (1954, 'Médecine', 'Thomas H. Weller'),
       (1954, 'Paix', 'Office of the United Nations High Commissioner for Refugees'),
       (1954, 'Physique', 'Max Born'),
       (1954, 'Physique', 'Walther Bothe'),
       (1953, 'Chimie', 'Hermann Staudinger'),
       (1953, 'Literature', 'Winston Churchill'),
       (1953, 'Médecine', 'Hans Krebs'),
       (1953, 'Médecine', 'Fritz Lipmann'),
       (1953, 'Paix', 'George C. Marshall'),
       (1953, 'Physique', 'Frits Zernike'),
       (1952, 'Chimie', 'Archer J.P. Martin'),
       (1952, 'Chimie', 'Richard L.M. Synge'),
       (1952, 'Literature', 'François Mauriac'),
       (1952, 'Médecine', 'Selman A. Waksman'),
       (1952, 'Paix', 'Albert Schweitzer'),
       (1952, 'Physique', 'Felix Bloch'),
       (1952, 'Physique', 'E. M. Purcell'),
       (1951, 'Chimie', 'Edwin M. McMillan'),
       (1951, 'Chimie', 'Glenn T. Seaborg'),
       (1951, 'Literature', 'Pär Lagerkvist'),
       (1951, 'Médecine', 'Max Theiler'),
       (1951, 'Paix', 'Léon Jouhaux'),
       (1951, 'Physique', 'John Cockcroft'),
       (1951, 'Physique', 'Ernest T.S. Walton'),
       (1950, 'Chimie', 'Kurt Alder'),
       (1950, 'Chimie', 'Otto Diels'),
       (1950, 'Literature', 'Bertrand Russell'),
       (1950, 'Médecine', 'Philip S. Hench'),
       (1950, 'Médecine', 'Edward C. Kendall'),
       (1950, 'Médecine', 'Tadeus Reichstein'),
       (1950, 'Paix', 'Ralph Bunche'),
       (1950, 'Physique', 'Cecil Powell'),
       (1949, 'Chimie', 'William F. Giauque'),
       (1949, 'Literature', 'William Faulkner'),
       (1949, 'Médecine', 'Walter Hess'),
       (1949, 'Médecine', 'Egas Moniz'),
       (1949, 'Paix', 'Lord Boyd Orr'),
       (1949, 'Physique', 'Hideki Yukawa'),
       (1948, 'Chimie', 'Arne Tiselius'),
       (1948, 'Literature', 'T.S. Eliot'),
       (1948, 'Médecine', 'Paul Müller'),
       (1948, 'Physique', 'Patrick M.S. Blackett'),
       (1947, 'Chimie', 'Sir Robert Robinson'),
       (1947, 'Literature', 'André Gide'),
       (1947, 'Médecine', 'Carl Cori'),
       (1947, 'Médecine', 'Gerty Cori'),
       (1947, 'Médecine', 'Bernardo Houssay'),
       (1947, 'Paix', 'Friends Service Council'),
       (1947, 'Paix', 'American Friends Service Committee'),
       (1947, 'Physique', 'Edward V. Appleton'),
       (1946, 'Chimie', 'John H. Northrop'),
       (1946, 'Chimie', 'Wendell M. Stanley'),
       (1946, 'Chimie', 'James B. Sumner'),
       (1946, 'Literature', 'Hermann Hesse'),
       (1946, 'Médecine', 'Hermann J. Muller'),
       (1946, 'Paix', 'Emily Greene Balch'),
       (1946, 'Paix', 'John R. Mott'),
       (1946, 'Physique', 'Percy W. Bridgman'),
       (1945, 'Chimie', 'Artturi Virtanen'),
       (1945, 'Literature', 'Gabriela Mistral'),
       (1945, 'Médecine', 'Ernst B. Chain'),
       (1945, 'Médecine', 'Sir Alexander Fleming'),
       (1945, 'Médecine', 'Sir Howard Florey'),
       (1945, 'Paix', 'Cordell Hull'),
       (1945, 'Physique', 'Wolfgang Pauli'),
       (1944, 'Chimie', 'Otto Hahn'),
       (1944, 'Literature', 'Johannes V. Jensen'),
       (1944, 'Médecine', 'Joseph Erlanger'),
       (1944, 'Médecine', 'Herbert S. Gasser'),
       (1944, 'Paix', 'International Committee of the Red Cross'),
       (1944, 'Physique', 'Isidor Isaac Rabi'),
       (1943, 'Chimie', 'George de Hevesy'),
       (1943, 'Médecine', 'Henrik Dam'),
       (1943, 'Médecine', 'Edward A. Doisy'),
       (1943, 'Physique', 'Otto Stern'),
       (1939, 'Chimie', 'Adolf Butenandt'),
       (1939, 'Chimie', 'Leopold Ruzicka'),
       (1939, 'Literature', 'Frans Eemil Sillanpää'),
       (1939, 'Médecine', 'Gerhard Domagk'),
       (1939, 'Physique', 'Ernest Lawrence'),
       (1938, 'Chimie', 'Richard Kuhn'),
       (1938, 'Literature', 'Pearl Buck'),
       (1938, 'Médecine', 'Corneille Heymans'),
       (1938, 'Paix', 'Nansen International Office for Refugees'),
       (1938, 'Physique', 'Enrico Fermi'),
       (1937, 'Chimie', 'Norman Haworth'),
       (1937, 'Chimie', 'Paul Karrer'),
       (1937, 'Literature', 'Roger Martin du Gard'),
       (1937, 'Médecine', 'Albert Szent-Györgyi'),
       (1937, 'Paix', 'Robert Cecil'),
       (1937, 'Physique', 'Clinton Davisson'),
       (1937, 'Physique', 'George Paget Thomson'),
       (1936, 'Chimie', 'Peter Debye'),
       (1936, 'Literature', 'Eugene O''''Neill'),
       (1936, 'Médecine', 'Sir Henry Dale'),
       (1936, 'Médecine', 'Otto Loewi'),
       (1936, 'Paix', 'Carlos Saavedra Lamas'),
       (1936, 'Physique', 'Carl D. Anderson'),
       (1936, 'Physique', 'Victor F. Hess'),
       (1935, 'Chimie', 'Frédéric Joliot'),
       (1935, 'Chimie', 'Irène Joliot-Curie'),
       (1935, 'Médecine', 'Hans Spemann'),
       (1935, 'Paix', 'Carl von Ossietzky'),
       (1935, 'Physique', 'James Chadwick'),
       (1934, 'Chimie', 'Harold C. Urey'),
       (1934, 'Literature', 'Luigi Pirandello'),
       (1934, 'Médecine', 'George R. Minot'),
       (1934, 'Médecine', 'William P. Murphy'),
       (1934, 'Médecine', 'George H. Whipple'),
       (1934, 'Paix', 'Arthur Henderson'),
       (1933, 'Literature', 'Ivan Bunin'),
       (1933, 'Médecine', 'Thomas H. Morgan'),
       (1933, 'Paix', 'Sir Norman Angell'),
       (1933, 'Physique', 'Paul A.M. Dirac'),
       (1933, 'Physique', 'Erwin Schrödinger'),
       (1932, 'Chimie', 'Irving Langmuir'),
       (1932, 'Literature', 'John Galsworthy'),
       (1932, 'Médecine', 'Edgar Adrian'),
       (1932, 'Médecine', 'Sir Charles Sherrington'),
       (1932, 'Physique', 'Werner Heisenberg'),
       (1931, 'Chimie', 'Friedrich Bergius'),
       (1931, 'Chimie', 'Carl Bosch'),
       (1931, 'Literature', 'Erik Axel Karlfeldt'),
       (1931, 'Médecine', 'Otto Warburg'),
       (1931, 'Paix', 'Jane Addams'),
       (1931, 'Paix', 'Nicholas Murray Butler'),
       (1930, 'Chimie', 'Hans Fischer'),
       (1930, 'Literature', 'Sinclair Lewis'),
       (1930, 'Médecine', 'Karl Landsteiner'),
       (1930, 'Paix', 'Nathan Söderblom'),
       (1930, 'Physique', 'Sir Venkata Raman'),
       (1929, 'Chimie', 'Arthur Harden'),
       (1929, 'Chimie', 'Hans von Euler-Chelpin'),
       (1929, 'Literature', 'Thomas Mann'),
       (1929, 'Médecine', 'Christiaan Eijkman'),
       (1929, 'Médecine', 'Sir Frederick Hopkins'),
       (1929, 'Paix', 'Frank B. Kellogg'),
       (1929, 'Physique', 'Louis de Broglie'),
       (1928, 'Chimie', 'Adolf Windaus'),
       (1928, 'Literature', 'Sigrid Undset'),
       (1928, 'Médecine', 'Charles Nicolle'),
       (1928, 'Physique', 'Owen Willans Richardson'),
       (1927, 'Chimie', 'Heinrich Wieland'),
       (1927, 'Literature', 'Henri Bergson'),
       (1927, 'Médecine', 'Julius Wagner-Jauregg'),
       (1927, 'Paix', 'Ferdinand Buisson'),
       (1927, 'Paix', 'Ludwig Quidde'),
       (1927, 'Physique', 'Arthur H. Compton'),
       (1927, 'Physique', 'C.T.R. Wilson'),
       (1926, 'Chimie', 'The Svedberg'),
       (1926, 'Literature', 'Grazia Deledda'),
       (1926, 'Médecine', 'Johannes Fibiger'),
       (1926, 'Paix', 'Aristide Briand'),
       (1926, 'Paix', 'Gustav Stresemann'),
       (1926, 'Physique', 'Jean Baptiste Perrin'),
       (1925, 'Chimie', 'Richard Zsigmondy'),
       (1925, 'Literature', 'George Bernard Shaw'),
       (1925, 'Paix', 'Sir Austen Chamberlain'),
       (1925, 'Paix', 'Charles G. Dawes'),
       (1925, 'Physique', 'James Franck'),
       (1925, 'Physique', 'Gustav Hertz'),
       (1924, 'Literature', 'Wladyslaw Reymont'),
       (1924, 'Médecine', 'Willem Einthoven'),
       (1924, 'Physique', 'Manne Siegbahn'),
       (1923, 'Chimie', 'Fritz Pregl'),
       (1923, 'Literature', 'William Butler Yeats'),
       (1923, 'Médecine', 'Frederick G. Banting'),
       (1923, 'Médecine', 'John Macleod'),
       (1923, 'Physique', 'Robert A. Millikan'),
       (1922, 'Chimie', 'Francis W. Aston'),
       (1922, 'Literature', 'Jacinto Benavente'),
       (1922, 'Médecine', 'Archibald V. Hill'),
       (1922, 'Médecine', 'Otto Meyerhof'),
       (1922, 'Paix', 'Fridtjof Nansen'),
       (1922, 'Physique', 'Niels Bohr'),
       (1921, 'Chimie', 'Frederick Soddy'),
       (1921, 'Literature', 'Anatole France'),
       (1921, 'Paix', 'Hjalmar Branting'),
       (1921, 'Paix', 'Christian Lange'),
       (1921, 'Physique', 'Albert Einstein'),
       (1920, 'Chimie', 'Walther Nernst'),
       (1920, 'Literature', 'Knut Hamsun'),
       (1920, 'Médecine', 'August Krogh'),
       (1920, 'Paix', 'Léon Bourgeois'),
       (1920, 'Physique', 'Charles Edouard Guillaume'),
       (1919, 'Literature', 'Carl Spitteler'),
       (1919, 'Médecine', 'Jules Bordet'),
       (1919, 'Paix', 'Woodrow Wilson'),
       (1919, 'Physique', 'Johannes Stark'),
       (1918, 'Chimie', 'Fritz Haber'),
       (1918, 'Physique', 'Max Planck'),
       (1917, 'Literature', 'Karl Gjellerup'),
       (1917, 'Literature', 'Henrik Pontoppidan'),
       (1917, 'Paix', 'International Committee of the Red Cross'),
       (1917, 'Physique', 'Charles Glover Barkla'),
       (1916, 'Literature', 'Verner von Heidenstam'),
       (1915, 'Chimie', 'Richard Willstätter'),
       (1915, 'Literature', 'Romain Rolland'),
       (1915, 'Physique', 'William Bragg'),
       (1915, 'Physique', 'Lawrence Bragg'),
       (1914, 'Chimie', 'Theodore W. Richards'),
       (1914, 'Médecine', 'Robert Bárány'),
       (1914, 'Physique', 'Max von Laue'),
       (1913, 'Chimie', 'Alfred Werner'),
       (1913, 'Literature', 'Rabindranath Tagore'),
       (1913, 'Médecine', 'Charles Richet'),
       (1913, 'Paix', 'Henri La Fontaine'),
       (1913, 'Physique', 'Heike Kamerlingh Onnes'),
       (1912, 'Chimie', 'Victor Grignard'),
       (1912, 'Chimie', 'Paul Sabatier'),
       (1912, 'Literature', 'Gerhart Hauptmann'),
       (1912, 'Médecine', 'Alexis Carrel'),
       (1912, 'Paix', 'Elihu Root'),
       (1912, 'Physique', 'Gustaf Dalén'),
       (1911, 'Chimie', 'Marie Curie'),
       (1911, 'Literature', 'Maurice Maeterlinck'),
       (1911, 'Médecine', 'Allvar Gullstrand'),
       (1911, 'Paix', 'Tobias Asser'),
       (1911, 'Paix', 'Alfred Fried'),
       (1911, 'Physique', 'Wilhelm Wien'),
       (1910, 'Chimie', 'Otto Wallach'),
       (1910, 'Literature', 'Paul Heyse'),
       (1910, 'Médecine', 'Albrecht Kossel'),
       (1910, 'Paix', 'Permanent International Paix Bureau'),
       (1910, 'Physique', 'Johannes Diderik van der Waals'),
       (1909, 'Chimie', 'Wilhelm Ostwald'),
       (1909, 'Literature', 'Selma Lagerlöf'),
       (1909, 'Médecine', 'Theodor Kocher'),
       (1909, 'Paix', 'Auguste Beernaert'),
       (1909, 'Paix', 'Paul Henri d''''Estournelles de Constant'),
       (1909, 'Physique', 'Ferdinand Braun'),
       (1909, 'Physique', 'Guglielmo Marconi'),
       (1908, 'Chimie', 'Ernest Rutherford'),
       (1908, 'Literature', 'Rudolf Eucken'),
       (1908, 'Médecine', 'Paul Ehrlich'),
       (1908, 'Médecine', 'Ilya Mechnikov'),
       (1908, 'Paix', 'Klas Pontus Arnoldson'),
       (1908, 'Paix', 'Fredrik Bajer'),
       (1908, 'Physique', 'Gabriel Lippmann'),
       (1907, 'Chimie', 'Eduard Buchner'),
       (1907, 'Literature', 'Rudyard Kipling'),
       (1907, 'Médecine', 'Alphonse Laveran'),
       (1907, 'Paix', 'Ernesto Teodoro Moneta'),
       (1907, 'Paix', 'Louis Renault'),
       (1907, 'Physique', 'Albert A. Michelson'),
       (1906, 'Chimie', 'Henri Moissan'),
       (1906, 'Literature', 'Giosuè Carducci'),
       (1906, 'Médecine', 'Camillo Golgi'),
       (1906, 'Médecine', 'Santiago Ramón y Cajal'),
       (1906, 'Paix', 'Theodore Roosevelt'),
       (1906, 'Physique', 'J.J. Thomson'),
       (1905, 'Chimie', 'Adolf von Baeyer'),
       (1905, 'Literature', 'Henryk Sienkiewicz'),
       (1905, 'Médecine', 'Robert Koch'),
       (1905, 'Paix', 'Bertha von Suttner'),
       (1905, 'Physique', 'Philipp Lenard'),
       (1904, 'Chimie', 'Sir William Ramsay'),
       (1904, 'Literature', 'José Echegaray'),
       (1904, 'Literature', 'Frédéric Mistral'),
       (1904, 'Médecine', 'Ivan Pavlov'),
       (1904, 'Paix', 'Institute of International Law'),
       (1904, 'Physique', 'Lord Rayleigh'),
       (1903, 'Chimie', 'Svante Arrhenius'),
       (1903, 'Literature', 'Bjørnstjerne Bjørnson'),
       (1903, 'Médecine', 'Niels Ryberg Finsen'),
       (1903, 'Paix', 'Randal Cremer'),
       (1903, 'Physique', 'Henri Becquerel'),
       (1903, 'Physique', 'Pierre Curie'),
       (1903, 'Physique', 'Marie Curie'),
       (1902, 'Chimie', 'Emil Fischer'),
       (1902, 'Literature', 'Theodor Mommsen'),
       (1902, 'Médecine', 'Ronald Ross'),
       (1902, 'Paix', 'Élie Ducommun'),
       (1902, 'Paix', 'Albert Gobat'),
       (1902, 'Physique', 'Hendrik A. Lorentz'),
       (1902, 'Physique', 'Pieter Zeeman'),
       (1901, 'Chimie', 'Jacobus H. van ''''t Hoff'),
       (1901, 'Literature', 'Sully Prudhomme'),
       (1901, 'Médecine', 'Emil von Behring'),
       (1901, 'Paix', 'Henry Dunant'),
       (1901, 'Paix', 'Frédéric Passy'),
       (1901, 'Physique', 'Wilhelm Conrad Röntgen');
COMMIT;
